name: go_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  parse_server_sdk_flutter:
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  autocomplete_textfield: ^2.0.1
  bitsdojo_window: ^0.1.5
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: assets\fonts\Rubik-SemiBold.ttf
        - asset: assets\fonts\Rubik-Regular.ttf
